excluded:
  - Pods

included:
  - ../CommonWallet/
  - CommonWallet

disabled_rules:
  - trailing_newline
  - trailing_whitespace
  - opening_brace
  - trailing_comma
  - vertical_whitespace
  - orphaned_doc_comment
