source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'CommonWallet_Example' do
  pod 'CommonWallet/Core', :path => '../'
  pod 'CommonWallet/IrohaMiddleware', :path => '../'
  pod 'SwiftLint', '~> 0.39'
  pod 'OHHTTPStubs/Swift'
  pod 'Fabric', '= 1.9.0'
  pod 'Crashlytics', '= 3.12.0'
  pod 'SwiftGen'

  target 'CommonWallet_Tests' do
    inherit! :search_paths

      pod 'Cuckoo'
      pod 'OHHTTPStubs/Swift'
  end
end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
