source 'https://github.com/soramitsu/podspec-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'CommonWallet_Example' do
  pod 'CommonWallet', :path => '../'
  pod 'SwiftLint', '= 0.31.0'
  pod 'FireMock'
  pod 'Fabric', '= 1.9.0'
  pod 'Crashlytics', '= 3.12.0'

  target 'CommonWallet_Tests' do
    inherit! :search_paths

      pod 'Cuckoo'
      pod 'FireMock'
  end
end

post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
